### PR TITLE
Migrate to Vue 3 and Lumen 9

### PR DESCRIPTION
**Pull request by MrLucio**
Main changes to **FrontEnd**:
- Upgraded `Vue 2` to `Vue 3`
- Replaced `Vuex` with `Pinia` (actions can no longer be defined in a separate file, look at [this issue](https://github.com/vuejs/pinia/discussions/983))
- Replaced `vue-notification` with `@kyvg/vue3-notification`
- Removed `vue-meta` (not used inside the project and not supporting Vue 3 at this moment)
- Ugraded `vue-i18n` to a Vue 3 friendly version
- Moved JS code from modules and components inside their `.vue` files because of  Vue 3 [separation of concerns](https://vuejs.org/guide/scaling-up/sfc.html#what-about-separation-of-concerns) rules.

Main changes to **BackEnd**:
- Upgraded `Lumen 7.0` to `Lumen 9.1.5`
- Upgraded `PHP 7.2.5` to `PHP 8.1.0`
- Upgraded `urameshibr/lumen-form-request`

### CODE REVIEW

**Comment by agattorno** [comment]
hello, i can't do:
composer install

your php version (8.1.10) does not satisfy that requirement

**Comment by MrLucio** [comment]
> hello, i can't do: composer install
> 
> your php version (8.1.10) does not satisfy that requirement

Hello, are you getting this error when running `composer install` on the fork I created on [https://github.com/MrLucio/vue-lumen-starter](https://github.com/MrLucio/vue-lumen-starter)?
If yes then I'd be confused since your version (8.1.10) is even higher than the minimum (8.1.0) stated in the composer.json file.

**Comment by agattorno** [comment]
i'm so sorry, it's working now. i do again the installation steeps and its working, i has clone the proyect using GitHub Desktop. The first time i was clone the code i use the Download ZIP.
I will try to do it again with the ZIP to try reproduce my error.

**Comment by gentritabazi** [comment]
No activities let's close thise.

**Comment by agattorno** [comment]
hello, i test againm the problem is in https://github.com/gentritabazi/vue-lumen-starter
in your fork https://github.com/MrLucio/vue-lumen-starter all be ok.

i don´t see in any place how i login in the frontend?

Thanks

**Pull request closed without merging**
